{
    parserClass="com.vistasoft.plugins.saltstack.parser.SaltStateParser"

    extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

    psiClassPrefix="SaltState"
    psiImplClassSuffix="Impl"
    psiPackage="com.vistasoft.plugins.saltstack.psi"
    psiImplPackage="com.vistasoft.plugins.saltstack.psi.impl"

    elementTypeHolderClass="com.vistasoft.plugins.saltstack.psi.SaltStateTypes"
    elementTypeClass="com.vistasoft.plugins.saltstack.psi.SaltStateElementType"
    tokenTypeClass="com.vistasoft.plugins.saltstack.psi.SaltStateTokenType"
}

saltStateFile           ::= item_*

private item_           ::= (COMMENT|inline_item_|structured_item)

# key: identifier
# - identifier # comment
# - key2: value # comment
# - key3:
#   subKey3.1: value
#

private inline_item_    ::= (inline_key_item|inline_list_item)
inline_key_item         ::= KEY (IDENTIFIER|STRING) COMMENT?
inline_list_item        ::= LIST_NODE (IDENTIFIER|STRING) COMMENT?

# key:
#   s1: value1
#   s2: value2
#   s3: ...

# key:
#   - value1
#   - value2
#   - ...
structured_item         ::= LIST_NODE? KEY COMMENT? INDENT item_*

